// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu7U93_DNjksPTNnClmkABKV2d0bdo0Sw',
    appId: '1:293999009610:web:6be2767f625cea5f782bb3',
    messagingSenderId: '293999009610',
    projectId: 'masar-spare',
    authDomain: 'masar-spare.firebaseapp.com',
    storageBucket: 'masar-spare.firebasestorage.app',
    measurementId: 'G-WJDX3E0M1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFaSe4EkZWiO3TTW2usf0OHQ219c4KPh0',
    appId: '1:293999009610:android:4943bb3373ea7ea2782bb3',
    messagingSenderId: '293999009610',
    projectId: 'masar-spare',
    storageBucket: 'masar-spare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Pe4TErERHjOlB6xidq7eLAfKYbmSUpg',
    appId: '1:293999009610:ios:5f2c8edf6cb23de0782bb3',
    messagingSenderId: '293999009610',
    projectId: 'masar-spare',
    storageBucket: 'masar-spare.firebasestorage.app',
    iosBundleId: 'com.example.masarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Pe4TErERHjOlB6xidq7eLAfKYbmSUpg',
    appId: '1:293999009610:ios:5f2c8edf6cb23de0782bb3',
    messagingSenderId: '293999009610',
    projectId: 'masar-spare',
    storageBucket: 'masar-spare.firebasestorage.app',
    iosBundleId: 'com.example.masarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu7U93_DNjksPTNnClmkABKV2d0bdo0Sw',
    appId: '1:293999009610:web:e25fb0e67e6ecf20782bb3',
    messagingSenderId: '293999009610',
    projectId: 'masar-spare',
    authDomain: 'masar-spare.firebaseapp.com',
    storageBucket: 'masar-spare.firebasestorage.app',
    measurementId: 'G-4LCV6MXDHQ',
  );

}