// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZo0naK8i4mLbyHi6nCtP453cFSE6lQSo',
    appId: '1:1050995001056:web:f79a26f3cf9908b5953285',
    messagingSenderId: '1050995001056',
    projectId: 'itiproject-ba6ab',
    authDomain: 'itiproject-ba6ab.firebaseapp.com',
    databaseURL: 'https://itiproject-ba6ab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itiproject-ba6ab.firebasestorage.app',
    measurementId: 'G-FZCFS1X458',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6yvp20I45uYf7myMg4Kxl0YihWwkRA4M',
    appId: '1:1050995001056:android:3968095cd581c411953285',
    messagingSenderId: '1050995001056',
    projectId: 'itiproject-ba6ab',
    databaseURL: 'https://itiproject-ba6ab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itiproject-ba6ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAliZIbOMEm6L_aEPW4PYxaox_khZo3M_M',
    appId: '1:1050995001056:ios:f37615fac608928a953285',
    messagingSenderId: '1050995001056',
    projectId: 'itiproject-ba6ab',
    databaseURL: 'https://itiproject-ba6ab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itiproject-ba6ab.firebasestorage.app',
    iosBundleId: 'com.example.masarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAliZIbOMEm6L_aEPW4PYxaox_khZo3M_M',
    appId: '1:1050995001056:ios:f37615fac608928a953285',
    messagingSenderId: '1050995001056',
    projectId: 'itiproject-ba6ab',
    databaseURL: 'https://itiproject-ba6ab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itiproject-ba6ab.firebasestorage.app',
    iosBundleId: 'com.example.masarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZo0naK8i4mLbyHi6nCtP453cFSE6lQSo',
    appId: '1:1050995001056:web:763b97c087bce194953285',
    messagingSenderId: '1050995001056',
    projectId: 'itiproject-ba6ab',
    authDomain: 'itiproject-ba6ab.firebaseapp.com',
    databaseURL: 'https://itiproject-ba6ab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'itiproject-ba6ab.firebasestorage.app',
    measurementId: 'G-MJ8MT4G2CJ',
  );
}
